[build]
  functions = "netlify/functions"
  publish = "build"

[dev]
  port = 8989
  targetPort = 3003

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200