# netlify.toml
[build]
  functions = "netlify/functions"
  publish = "build"

[dev]
  port = 8989
  targetPort = 3003

  [[redirects]]
  from = "api/v1/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200