module.exports.usersList = [
  {
    id: "EMP10018",
    name: "Harsh Verma",
    dob: "2000-02-17",
    designation: "Software Development Engineer 1",
    role: "Employee",
    managerId: "EMP10009",
    businessUnit: "Life Science",
    department: "Engineering",
    doj: "2023-04-23",
    managerName: "Ali Hassan",
  },
  {
    id: "EMP10002",
    name: "Harshita Vyas",
    dob: "1998-10-22",
    designation: "Software Development Engineer 1",
    role: "Employee",
    managerId: "EMP10000",
    businessUnit: "BFSI",
    department: "Engineering",
    doj: "2021-08-23",
    managerName: "Jane Doe",
  },
  {
    id: "EMP10022",
    name: "Jake Steve",
    dob: "1998-01-20",
    designation: "Software Development Engineer 1",
    role: "Employee",
    managerId: "EMP10007",
    businessUnit: "BFSI",
    department: "Bench",
    doj: "2020-11-11",
    managerName: "Ryan Lee",
  },
  {
    id: "EMP10017",
    name: "Tina Roy",
    dob: "1997-04-30",
    designation: "Human Resource Manager",
    role: "Human Resource Manager",
    managerId: "EMP10014",
    businessUnit: "BFSI",
    department: "Human Resources",
    doj: "2020-07-30",
    managerName: "Yuki Sato",
  },
  {
    id: "EMP10030",
    name: "Donna Doe",
    dob: "1993-06-23",
    designation: "Software Development Engineer 3",
    role: "Employee",
    managerId: "EMP10009",
    businessUnit: "Retail",
    department: "Engineering",
    doj: "2020-03-12",
    managerName: "Ali Hassan",
  },
  {
    id: "EMP10003",
    name: "Shubham Purohit",
    dob: "1998-10-22",
    designation: "Software Development Engineer 1",
    role: "Employee",
    managerId: "EMP10000",
    businessUnit: "BFSI",
    department: "Engineering",
    doj: "2020-02-12",
    managerName: "Jane Doe",
  },
  {
    id: "EMP10013",
    name: "Amelie Duval",
    dob: "1996-04-25",
    designation: "Software Development Engineer 1",
    role: "Employee",
    managerId: "EMP10009",
    businessUnit: "Life Science",
    department: "Engineering",
    doj: "2019-12-10",
    managerName: "Ali Hassan",
  },
  {
    id: "EMP10001",
    name: "John Doe",
    dob: "1997-04-17",
    designation: "Software Development Engineer 1",
    role: "Employee",
    managerId: "EMP10000",
    businessUnit: "Retail",
    department: "Engineering",
    doj: "2019-04-17",
    managerName: "Jane Doe",
  },
  {
    id: "EMP10024",
    name: "Aleena Gilbert",
    dob: "1995-01-12",
    designation: "Project Manager",
    role: "Manager",
    managerId: "EMP10024",
    businessUnit: "BFSI",
    department: "Business",
    doj: "2018-10-22",
    managerName: "Aleena Gilbert",
  },
  {
    id: "EMP10005",
    name: "Bella Kumar",
    dob: "1995-09-24",
    designation: "Software Development Engineer 1",
    role: "Employee",
    managerId: "EMP10000",
    businessUnit: "BFSI",
    department: "Engineering",
    doj: "2018-06-23",
    managerName: "Jane Doe",
  },
  {
    id: "EMP10019",
    name: "Neha Kapoor",
    dob: "1996-09-25",
    designation: "UI/UX Designer",
    role: "Employee",
    managerId: "EMP10015",
    businessUnit: "Logistics",
    department: "Engineering",
    doj: "2018-05-10",
    managerName: "Mohammed Ali",
  },
  {
    id: "EMP10008",
    name: "Emma Johnson",
    dob: "1995-09-17",
    designation: "Human Resource Manager",
    role: "Human Resource Manager",
    managerId: "EMP10014",
    businessUnit: "Logistics",
    department: "Human Resources",
    doj: "2017-11-24",
    managerName: "Yuki Sato",
  },
  {
    id: "EMP10004",
    name: "Bell Singh",
    dob: "1995-09-24",
    designation: "Software Development Engineer 1",
    role: "Employee",
    managerId: "EMP10000",
    businessUnit: "BFSI",
    department: "Engineering",
    doj: "2017-03-21",
    managerName: "Jane Doe",
  },
  {
    id: "EMP10023",
    name: "Anna Doe",
    dob: "1995-06-14",
    designation: "Software Development Engineer 2",
    role: "Employee",
    managerId: "EMP10015",
    businessUnit: "Logistics",
    department: "Engineering",
    doj: "2017-02-18",
    managerName: "Mohammed Ali",
  },
  {
    id: "EMP10016",
    name: "Ashok Kumar",
    dob: "1991-12-11",
    designation: "Software Development Engineer 3",
    role: "Employee",
    managerId: "EMP10009",
    businessUnit: "Life Science",
    department: "Engineering",
    doj: "2016-10-03",
    managerName: "Ali Hassan",
  },
  {
    id: "EMP10012",
    name: "Li Yuan",
    dob: "1994-11-11",
    designation: "Software Development Engineer 2",
    role: "Employee",
    managerId: "EMP10009",
    businessUnit: "Logistics",
    department: "Engineering",
    doj: "2016-08-09",
    managerName: "Ali Hassan",
  },
  {
    id: "EMP10021",
    name: "Maria Smith",
    dob: "1993-07-22",
    designation: "Software Development Engineer 3",
    role: "Employee",
    managerId: "EMP10015",
    businessUnit: "Logistics",
    department: "Engineering",
    doj: "2016-02-14",
    managerName: "Mohammed Ali",
  },
  {
    id: "EMP10015",
    name: "Mohammed Ali",
    dob: "1991-10-09",
    designation: "Project Manager",
    role: "Manager",
    managerId: "EMP10010",
    businessUnit: "Logistics",
    department: "Engineering",
    doj: "2015-10-22",
    managerName: "Anika Sharma",
  },
  {
    id: "EMP10000",
    name: "Jane Doe",
    dob: "1992-01-17",
    designation: "Project Manager",
    role: "Manager",
    managerId: "EMP10010",
    businessUnit: "BFSI",
    department: "Business",
    doj: "2015-09-19",
    managerName: "Anika Sharma",
  },
  {
    id: "EMP10010",
    name: "Anika Sharma",
    dob: "1993-12-02",
    designation: "Senior Project Manager",
    role: "Manager",
    managerId: "EMP10007",
    businessUnit: "Logistics",
    department: "Engineering",
    doj: "2015-05-12",
    managerName: "Ryan Lee",
  },
  {
    id: "EMP10020",
    name: "Rohit Mehta",
    dob: "1992-03-10",
    designation: "Software Development Engineer 2",
    role: "Employee",
    managerId: "EMP10015",
    businessUnit: "Logistics",
    department: "Engineering",
    doj: "2014-09-24",
    managerName: "Mohammed Ali",
  },
  {
    id: "EMP10011",
    name: "Carlos Garcia",
    dob: "1992-08-30",
    designation: "Human Resource Manager",
    role: "Human Resource Manager",
    managerId: "EMP10014",
    businessUnit: "Retail",
    department: "Human Resources",
    doj: "2014-01-01",
    managerName: "Yuki Sato",
  },
  {
    id: "EMP10026",
    name: "John Wick",
    dob: "1989-11-12",
    designation: "Project Manager",
    role: "Manager",
    managerId: "EMP0024",
    businessUnit: "BFSI",
    department: "Business",
    doj: "2012-10-20",
    managerName: " ",
  },
  {
    id: "EMP10007",
    name: "Ryan Lee",
    dob: "1990-03-22",
    designation: "Delivery Manager",
    role: "Delivery Manager",
    managerId: "EMP10007",
    businessUnit: "BFSI",
    department: "Business",
    doj: "2012-07-29",
    managerName: "Ryan Lee",
  },
  {
    id: "EMP10006",
    name: "Lucy Brown",
    dob: "1989-11-12",
    designation: "Human Resource Manager",
    role: "Human Resource Manager",
    managerId: "EMP10014",
    businessUnit: "Hospitality",
    department: "Human Resources",
    doj: "2011-06-30",
    managerName: "Yuki Sato",
  },
  {
    id: "EMP10014",
    name: "Yuki Sato",
    dob: "1988-06-15",
    designation: "Senior Human Resource Manager",
    role: "Human Resource Manager",
    managerId: "EMP10007",
    businessUnit: "Life Science",
    department: "Human Resources",
    doj: "2010-03-04",
    managerName: "Ryan Lee",
  },
  {
    id: "EMP10009",
    name: "Ali Hassan",
    dob: "1987-05-05",
    designation: "Project Manager",
    role: "Manager",
    managerId: "EMP10010",
    businessUnit: "Life Science",
    department: "Business",
    doj: "2009-05-01",
    managerName: "Anika Sharma",
  },
  {
    id: "EMP10038",
    name: "Saif Ali Khan",
    dob: "1978-06-23",
    designation: "Software Development Engineer 1",
    role: "Employee",
    managerId: "EMP10009",
    businessUnit: "BFSI",
    department: "Business",
    doj: "1999-09-19",
    managerName: "Ali Hassan",
  },
  {
    id: "EMP10035",
    name: "Selmon Bhoi",
    dob: "1972-06-23",
    designation: "Software Development Engineer 1",
    role: "Employee",
    managerId: "EMP10009",
    businessUnit: "BFSI",
    department: "Business",
    doj: "1996-09-19",
    managerName: "Ali Hassan",
  },
  {
    id: "EMP10034",
    name: "Salman Khan",
    dob: "1972-06-23",
    designation: "Delivery Manager",
    role: "Delivery Manager",
    managerId: "EMP10009",
    businessUnit: "BFSI",
    department: "Business",
    doj: "1996-09-19",
    managerName: "Ali Hassan",
  },
  {
    id: "EMP10025",
    name: "Karl Marx",
    dob: "1969-10-17",
    designation: "Delivery Manager",
    role: "Delivery Manager",
    managerId: "EMP10007",
    businessUnit: "BFSI",
    department: "Business",
    doj: "1975-07-12",
    managerName: "Ryan Lee",
  },
];
